---
- hosts: dev
  become: True
  tasks:
      - name: Start the container
        docker_container:
          name: vertex
          image: "nbktechnosys/myjavaproject8jun" 
          state: started
         
          published_ports:
           - 0.0.0.0:8080:8080
