---
- hosts: dev
  become: true

  tasks:
    - name: install pip
      package:
       name: python3-pip
       state: present
       update_cache: true

    - name: install docker sdk
      pip:
       name: docker

    - name: start docker service
      service:
        name: docker
        state: started

    - name: ensure a container is running
      docker_container:
        name: my_container
        state: present
        image: "nbktechnosys/myjavaproject8jun"
        exposed_ports: 8081
          
