---
- hosts: dev
  become: true

  tasks:
    - name: install pip
      package:
       name: python3-pip
       state: present
       update_cache: true
  
    - name: ensure a container is running
      docker_container:
        name: my_container
        state: started
        image: "nbktechnosys/myjavaproject8jun"
        pull: true
        ports:
           - 0.0.0.0:8080:8080
       
         
          
